---
- name: Vault Demo
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml

  tasks:
    - name: Show secret variable is loaded
      debug:
        msg: "Device password is loaded safely"

    - name: Use SNMP community
      debug:
        msg: "SNMP community string is configured"
